name: Build images

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '20 2 * * SAT'

jobs:
  multi:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        release:
          - buster
          - bullseye
          - bookworm
          #- sid
          #- experimental

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      -
        name: Extract metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            ${{ matrix.release }}
            type=schedule,prefix=${{ matrix.release }}-,pattern={{date 'YYYYMMDD'}}
            type=sha,prefix=${{ matrix.release }}-,format=short
          images: ghcr.io/${{ github.repository_owner }}/debian-pkgdevel
      -
        name: Extract metadata test
        id: docker_meta_test
        uses: docker/metadata-action@v4
        with:
          tags: |
            ${{ matrix.release }}
            type=schedule,prefix=${{ matrix.release }}-,pattern={{date 'YYYYMMDD'}}
            type=sha,prefix=${{ matrix.release }}-,format=short
          images: ghcr.io/${{ github.repository_owner }}/debian-pkgdevel-test
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      -
        name: Build and push test bookworm amd64
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: "DEBIAN_RELEASE=${{ matrix.release }}"
          #build-args: "DEBIAN_RELEASE=bookworm"
          #platforms: linux/amd64,linux/arm64,linux/arm,linux/386
          platforms: linux/amd64
          #push: ${{ github.ref == 'refs/heads/main' }}
          push: true
          tags: ${{ steps.docker_meta_test.outputs.tags }}
          labels: ${{ steps.docker_meta_test.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: "DEBIAN_RELEASE=${{ matrix.release }}"
          platforms: linux/amd64,linux/arm64,linux/arm,linux/386
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
