name: Build images

on:
  push:
    branches: main
  schedule:
    - cron: '20 2 * * SAT'

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Set release tag
        run: >
          RELEASE=$(grep -oP "(?<=DEBIAN_RELEASE=)[a-zA-Z]*$" Dockerfile)
          && echo "TAG=$RELEASE" >> $GITHUB_ENV
          && echo "RFC3339=$(date -u +'%Y-%m-%dT%H-%M-%SZ')" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/pgils/debian-pkgdevel:latest
            ghcr.io/pgils/debian-pkgdevel:${{ env.TAG }}
            ghcr.io/pgils/debian-pkgdevel:${{ env.TAG }}-${{ env.RFC3339 }}
